### ISSUE TITLE
【前端BUG】无法创建命名空间

### ISSUE THREAD

**Issue by barnettZQG** [alibaba/CNStackCommunityEdition#3]
![image](https://user-images.githubusercontent.com/18493394/154244321-a6c0e780-369e-45e4-bb5f-aabf225456d8.png)

**Comment by HaiyangDING** [comment]
请问，是按照这个方式操作的吗？

https://github.com/alibaba/CNStackCommunityEdition/blob/main/doc/first-app.md

**Comment by HaiyangDING** [comment]
你好，我初步试了一下，在我的环境里面没有复现这个问题。我们会尽快给出下一步反馈

**Comment by barnettZQG** [comment]
@HaiyangDING 看起来那应该是因为没有先开启集群的原因。这里前端代码应该也有BUG，建议优化，没有开启集群时做用户提示。

**Comment by HaiyangDING** [comment]
你好，请先检查下面的内容：
1. “基础设施-集群-cluster-local”确定是否开启
2. 按照 https://github.com/alibaba/CNStackCommunityEdition/blob/main/doc/first-app.md 看看是否有异常

如果不行，我们继续排查

**Comment by HaiyangDING** [comment]
> 

额，同时回复：）

嗯，这的确是一个前端的bug，我们会在下个版本修复。感谢

**Comment by luckyfengyong** [comment]
It has been fixed in 2.0.
