### ISSUE TITLE
单机版部署失败

### ISSUE THREAD

**Issue by wuyingjun-lucky** [alibaba/CNStackCommunityEdition#4]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/16109961/154397145-05a225cd-a515-4d80-88d0-50f03cbb416a.png">
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/16109961/154397188-fc510b90-e80f-4737-a1f2-c1f5ac148600.png">
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/16109961/154397210-6919c987-a066-45c6-a7a4-dca0b9fb507d.png">

**Comment by wuyingjun-lucky** [comment]
系统 ： centos 7.7

**Comment by HaiyangDING** [comment]
`lsblk`

看一下，有多少存储？

从最后一个图看，前面有存储不足导致的evict发生

**Comment by wuyingjun-lucky** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/16109961/154419749-a620ae65-d8e7-4088-a73f-554dfb10b1cd.png">

**Comment by HaiyangDING** [comment]
@wuyingjun-lucky 

抱歉，我没有说全。

`df -h` 

信息补充一下，这里我看不到磁盘的使用量

**Comment by wuyingjun-lucky** [comment]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/16109961/154420460-46ccc07b-42fb-41ed-bf08-2e587114452c.png">

**Comment by HaiyangDING** [comment]
@wuyingjun-lucky 

df -h  看起来没有问题

推荐两个方法：
1. `journalctl -u kubelet` 找一下和 eviction 有关系的日志，看看有什么线索
2. 参考 https://github.com/alibaba/CNStackCommunityEdition#%E6%B8%85%E7%90%86%E9%83%A8%E7%BD%B2 清理一下，重新部署

**Comment by wuyingjun-lucky** [comment]
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/16109961/154632611-ca7b8795-fcf2-4a55-b234-d6f3d2dba911.png">

**Comment by wuyingjun-lucky** [comment]
卸载重装了很多次了，每次的问题一样

**Comment by HaiyangDING** [comment]
嗨，麻烦把docker和kubelet的日志打包发给我吧，我看看是否可以找到线索 ***@***.*** journalctl -u docker journalctl -u kubelet 获取日志 在2022年02月18日 14:53，wuyingjun 写道： 卸载重装了很多次了，每次的问题一样 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by wuyingjun-lucky** [comment]
换了操作系统可以了。我想问下 你们 cnstack 社区版 可以看到 for edge吗

**Comment by luckyfengyong** [comment]
@wuyingjun-lucky 下一个版本（四月初）会提供应用目录，for edge会以平台增量服务的形式上架应用目录。

**Comment by luckyfengyong** [comment]
@wuyingjun-lucky 如果是因为操作系统的原因。可以说明一下有问题的操作系统类型和版本吗？我们可以关闭这个issue吗？

**Comment by wuyingjun-lucky** [comment]
7.7不行
8.*可以
可以关
