### ISSUE TITLE
Unable to instuall CNStack because of swap.

### ISSUE THREAD

**Issue by NikolaChen2017** [alibaba/CNStackCommunityEdition#5]
OS: Fedora35
Before the installation, I had run swapoff -a, and run free -h, checked whether the swap had been off.
[root@fedora ~]# free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       2.1Gi       3.4Gi       538Mi         9Gi        12Gi
Swap:             0B          0B          0B

Still got swap didnot disable error.
![image](https://user-images.githubusercontent.com/37110441/159483359-4369c948-3a43-4445-836b-5ad967811f40.png)

**Comment by luckyfengyong** [comment]
@NikolaChen2017 

Fedora35 is not officially supported by CNStack. You cloud try CentOS 7.8 and above.

CNStack is leveraging `kubeadm` to deploy Kubernetes cluster. The error message you met is returned by `kubeadm init` command to check whether the OS configuration meet the installation requirement or not.  Please refer to https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L645-L667 for the details. 

To make sure `swap off` is configured correctly, you could check whether the command of `cat /proc/swaps`  returns any content.
