### ISSUE TITLE
请问有开源计划吗？

### ISSUE THREAD

**Issue by tkgeng** [alibaba/CNStackCommunityEdition#6]

**Comment by luckyfengyong** [comment]
@tkgeng CNStack是阿里云面向企业级私有化云原生 PaaS 产品家族，具体减少请参考 https://cn.aliyun.com/activity/middleware/cnstack 。社区版是供用户免费下载安装，体验，创建研发环境的版本，目标是提供近似商业版本的用户体验。CNStack的很多服务都是基于开源项目创建的，例如容器平台的ACK Distro，中间件的rocketmq等等。

但是整个CNStack产品家族并不是完全开源的。您是想基于CNStack社区版扩展PaaS平台能力，还是想对产品由更多的控制。如果了解了背后的诉求，可以提供更好的帮助和回答。

**Comment by luckyfengyong** [comment]
开源策略在计划中
