### ISSUE TITLE
接入集群镜像pull需认证

### ISSUE THREAD

**Issue by junfsir** [alibaba/CNStackCommunityEdition#8]
Failed to pull image "ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ocm-deployer:v1.5.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ocm-deployer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by luckyfengyong** [comment]
@junfsir 可以使用2.0 版本。之前版本的镜像仓库在维护时，可能会有暂时的不可外部访问窗口期。
